stages:
  - build_docker
  - deploy

docker_build:
  stage: build_docker
  image: docker:latest
  services:
    - docker:latest
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --cache-from "$CI_REGISTRY_IMAGE:latest" -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA-$CI_COMMIT_BRANCH" .
    - docker tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA-$CI_COMMIT_BRANCH" "$CI_REGISTRY_IMAGE:latest"
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA-$CI_COMMIT_BRANCH"
    - docker push "$CI_REGISTRY_IMAGE:latest"
  only:
    - master
    - main
    - ci-test
deploy:
  stage: deploy
  when: manual
  trigger:
    project: "czujniki/infra"
    branch: "main"
    strategy: depend
    forward:
      pipeline_variables: true
  variables:
    BACKEND_IMAGE_TAG: "$CI_COMMIT_SHORT_SHA-$CI_COMMIT_BRANCH"
  only:
    - main
    - master