version: '3.8'

services:
  postgres-db-local:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=kamil.golawski
      - POSTGRES_PASSWORD=secret
    ports:
      - '34250:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
