###
GET http://localhost:8080/api/sensor/1

###
GET http://localhost:8080/api/sensor/1/live

### Paginacja
GET https://back.dev.skni.umcs.pl/api/sensor/1/data?startDate=2025-03-12T15:14:00&page=0&size=8

### Paginacja
GET http://localhost:8080/api/sensor/1/data?startDate=2025-03-12T15:23:45.000Z&page=1&size=8

###
GET http://localhost:8080/api/sensor/all

###
GET http://localhost:8080/api/sensor/all/live

### Paginacja
GET http://localhost:8080/api/sensor/all/data?startDate=2025-03-03T23:00:00&endDate=2025-03-03T23:30:00&page=0&size=8

###
GET http://localhost:8080/api/sensor/faculty/MFI

### Paginacja
GET http://localhost:8080/api/sensor/faculty/WPIA/data?startDate=2025-03-03T23:00:00&endDate=2025-03-03T23:30:00&page=0&
    size=8

###
POST https://back.dev.skni.umcs.pl/api/sensor/refresh-rates
X-API-KEY:
Content-Type: application/json

[
  {
    "sensorId": 1,
    "refreshRate": 60
  },
  {
    "sensorId": 2,
    "refreshRate": 60
  },
  {
    "sensorId": 3,
    "refreshRate": 60
  },
  {
    "sensorId": 4,
    "refreshRate": 60
  },
  {
    "sensorId": 5,
    "refreshRate": 60
  }
]



